/**
 * Copyright IBM Corp. 2021, 2026
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktn get
Object.defineProperty(exports, 'dataPlaneResource', { get: function () { return require('./data-plane-resource'); } });
Object.defineProperty(exports, 'resource', { get: function () { return require('./resource'); } });
Object.defineProperty(exports, 'resourceAction', { get: function () { return require('./resource-action'); } });
Object.defineProperty(exports, 'updateResource', { get: function () { return require('./update-resource'); } });
Object.defineProperty(exports, 'dataAzapiClientConfig', { get: function () { return require('./data-azapi-client-config'); } });
Object.defineProperty(exports, 'dataAzapiDataPlaneResource', { get: function () { return require('./data-azapi-data-plane-resource'); } });
Object.defineProperty(exports, 'dataAzapiResource', { get: function () { return require('./data-azapi-resource'); } });
Object.defineProperty(exports, 'dataAzapiResourceAction', { get: function () { return require('./data-azapi-resource-action'); } });
Object.defineProperty(exports, 'dataAzapiResourceId', { get: function () { return require('./data-azapi-resource-id'); } });
Object.defineProperty(exports, 'dataAzapiResourceList', { get: function () { return require('./data-azapi-resource-list'); } });
Object.defineProperty(exports, 'ephemeralAzapiDataPlaneResource', { get: function () { return require('./ephemeral-azapi-data-plane-resource'); } });
Object.defineProperty(exports, 'ephemeralAzapiResourceAction', { get: function () { return require('./ephemeral-azapi-resource-action'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });
Object.defineProperty(exports, 'providerFunctions', { get: function () { return require('./provider-functions'); } });

